//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices.Connected_Services.SDRADataAccessWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Name="SDRA External Interface Data Access Web ServiceSoap", Namespace="http://www.baesystems.com/schemas/sdra/dataaccess", ConfigurationName="SDRADataAccessWebService.SDRAExternalInterfaceDataAccessWebServiceSoap")]
    public interface SDRAExternalInterfaceDataAccessWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetDocumentsByPoint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.Document[]> GetDocumentsByPointAsync(SDRADataAccessWebService.Point searchPoint, int buffer, System.DateTime registrationDate, int docTypeId, int recommendedActionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetDocumentsByLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.Document[]> GetDocumentsByLineAsync(SDRADataAccessWebService.Line searchLine, int buffer, System.DateTime registrationDate, int docTypeId, int recommendedActionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetDocumentsByPolygon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.Document[]> GetDocumentsByPolygonAsync(SDRADataAccessWebService.Polygon searchPolygon, int buffer, System.DateTime registrationDate, int docTypeId, int recommendedActionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetDocumentsFromList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.Document[]> GetDocumentsFromListAsync(int[] sdocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetDocumentForViewing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.CallOutcome> GetDocumentForViewingAsync(string callerCode, int sdocId, string writeableFolderName, bool imageAsGeoTIFF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetDocumentRequestQueueStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.ProcessingStatus[]> GetDocumentRequestQueueStatusAsync(string callerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/ClearDocumentRequestJobFromQueu" +
            "e", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.CallOutcome> ClearDocumentRequestJobFromQueueAsync(string callerCode, int sdocId, string writeableFolderName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/ClearDocumentRequestQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.CallOutcome> ClearDocumentRequestQueueAsync(string callerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetDocumentMetadata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetDocumentMetadataAsync(int sdocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetDocumentRegistrationDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.DateTime> GetDocumentRegistrationDateAsync(int sdocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetDocumentAssessments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.DocumentAction[]> GetDocumentAssessmentsAsync(int sdocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetDocumentActions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.ArrayOfXElement> GetDocumentActionsAsync(int sdocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetForwardDocumentLinks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.Link[]> GetForwardDocumentLinksAsync(int sdocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetBackwardDocumentLinks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.Link[]> GetBackwardDocumentLinksAsync(int sdocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetSEPDocumentLinks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.Document[]> GetSEPDocumentLinksAsync(int sdocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetAllDocumentTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.DocumentType[]> GetAllDocumentTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/dataaccess/GetAllRecommendedActionTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SDRADataAccessWebService.RecommendedActionType[]> GetAllRecommendedActionTypesAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.baesystems.com/schemas/sdra/dataaccess")]
    public partial class Point
    {
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.baesystems.com/schemas/sdra/dataaccess")]
    public partial class RecommendedActionType
    {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.baesystems.com/schemas/sdra/dataaccess")]
    public partial class DocumentType
    {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.baesystems.com/schemas/sdra/dataaccess")]
    public partial class Link
    {
        
        private int docId1Field;
        
        private int docId2Field;
        
        private string linkTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DocId1
        {
            get
            {
                return this.docId1Field;
            }
            set
            {
                this.docId1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DocId2
        {
            get
            {
                return this.docId2Field;
            }
            set
            {
                this.docId2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LinkType
        {
            get
            {
                return this.linkTypeField;
            }
            set
            {
                this.linkTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.baesystems.com/schemas/sdra/dataaccess")]
    public partial class DocumentAction
    {
        
        private int idField;
        
        private string nameField;
        
        private int documentIdField;
        
        private int branchIdField;
        
        private string assessActionTypeField;
        
        private string verifyActionTypeField;
        
        private int assessUserField;
        
        private System.DateTime assessDateField;
        
        private string assessCommentsField;
        
        private int verifyUserField;
        
        private System.DateTime verifyDateField;
        
        private string verifyCommentsField;
        
        private byte[] snapshotField;
        
        private int productDocumentIdField;
        
        private string assessUserNameField;
        
        private string verifyUserNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BranchId
        {
            get
            {
                return this.branchIdField;
            }
            set
            {
                this.branchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AssessActionType
        {
            get
            {
                return this.assessActionTypeField;
            }
            set
            {
                this.assessActionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string VerifyActionType
        {
            get
            {
                return this.verifyActionTypeField;
            }
            set
            {
                this.verifyActionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int AssessUser
        {
            get
            {
                return this.assessUserField;
            }
            set
            {
                this.assessUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime AssessDate
        {
            get
            {
                return this.assessDateField;
            }
            set
            {
                this.assessDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AssessComments
        {
            get
            {
                return this.assessCommentsField;
            }
            set
            {
                this.assessCommentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int VerifyUser
        {
            get
            {
                return this.verifyUserField;
            }
            set
            {
                this.verifyUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime VerifyDate
        {
            get
            {
                return this.verifyDateField;
            }
            set
            {
                this.verifyDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string VerifyComments
        {
            get
            {
                return this.verifyCommentsField;
            }
            set
            {
                this.verifyCommentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=12)]
        public byte[] Snapshot
        {
            get
            {
                return this.snapshotField;
            }
            set
            {
                this.snapshotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ProductDocumentId
        {
            get
            {
                return this.productDocumentIdField;
            }
            set
            {
                this.productDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AssessUserName
        {
            get
            {
                return this.assessUserNameField;
            }
            set
            {
                this.assessUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string VerifyUserName
        {
            get
            {
                return this.verifyUserNameField;
            }
            set
            {
                this.verifyUserNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.baesystems.com/schemas/sdra/dataaccess")]
    public partial class ProcessingStatus
    {
        
        private int sdocIdField;
        
        private int errorCodeField;
        
        private System.DateTime statusTimeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SdocId
        {
            get
            {
                return this.sdocIdField;
            }
            set
            {
                this.sdocIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime StatusTime
        {
            get
            {
                return this.statusTimeField;
            }
            set
            {
                this.statusTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.baesystems.com/schemas/sdra/dataaccess")]
    public partial class CallOutcome
    {
        
        private int errorCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.baesystems.com/schemas/sdra/dataaccess")]
    public partial class Polygon
    {
        
        private int numPointsField;
        
        private Point[] pointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NumPoints
        {
            get
            {
                return this.numPointsField;
            }
            set
            {
                this.numPointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Point[] Points
        {
            get
            {
                return this.pointsField;
            }
            set
            {
                this.pointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.baesystems.com/schemas/sdra/dataaccess")]
    public partial class Line
    {
        
        private int numPointsField;
        
        private Point[] pointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NumPoints
        {
            get
            {
                return this.numPointsField;
            }
            set
            {
                this.numPointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Point[] Points
        {
            get
            {
                return this.pointsField;
            }
            set
            {
                this.pointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.baesystems.com/schemas/sdra/dataaccess")]
    public partial class Document
    {
        
        private int idField;
        
        private string nameField;
        
        private int documentTypeIdField;
        
        private string sourceNameField;
        
        private string spatialExtentPolygonField;
        
        private int cRSIdField;
        
        private string cRSParamsField;
        
        private int dTIdField;
        
        private string dTNameField;
        
        private int dTFromDatumField;
        
        private string dTMethodField;
        
        private double dTDxField;
        
        private double dTDyField;
        
        private double dTDzField;
        
        private double dTRxField;
        
        private double dTRyField;
        
        private double dTRzField;
        
        private double dTScaleField;
        
        private double dTAccuracyField;
        
        private string dTSourceFileField;
        
        private string dTStatusField;
        
        private string sepNameField;
        
        private int scaleField;
        
        private double spatialReferencingAccuracyField;
        
        private int statusField;
        
        private System.DateTime registrationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DocumentTypeId
        {
            get
            {
                return this.documentTypeIdField;
            }
            set
            {
                this.documentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SourceName
        {
            get
            {
                return this.sourceNameField;
            }
            set
            {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SpatialExtentPolygon
        {
            get
            {
                return this.spatialExtentPolygonField;
            }
            set
            {
                this.spatialExtentPolygonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CRSId
        {
            get
            {
                return this.cRSIdField;
            }
            set
            {
                this.cRSIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CRSParams
        {
            get
            {
                return this.cRSParamsField;
            }
            set
            {
                this.cRSParamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int DTId
        {
            get
            {
                return this.dTIdField;
            }
            set
            {
                this.dTIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DTName
        {
            get
            {
                return this.dTNameField;
            }
            set
            {
                this.dTNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int DTFromDatum
        {
            get
            {
                return this.dTFromDatumField;
            }
            set
            {
                this.dTFromDatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DTMethod
        {
            get
            {
                return this.dTMethodField;
            }
            set
            {
                this.dTMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double DTDx
        {
            get
            {
                return this.dTDxField;
            }
            set
            {
                this.dTDxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double DTDy
        {
            get
            {
                return this.dTDyField;
            }
            set
            {
                this.dTDyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double DTDz
        {
            get
            {
                return this.dTDzField;
            }
            set
            {
                this.dTDzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double DTRx
        {
            get
            {
                return this.dTRxField;
            }
            set
            {
                this.dTRxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double DTRy
        {
            get
            {
                return this.dTRyField;
            }
            set
            {
                this.dTRyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double DTRz
        {
            get
            {
                return this.dTRzField;
            }
            set
            {
                this.dTRzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double DTScale
        {
            get
            {
                return this.dTScaleField;
            }
            set
            {
                this.dTScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public double DTAccuracy
        {
            get
            {
                return this.dTAccuracyField;
            }
            set
            {
                this.dTAccuracyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string DTSourceFile
        {
            get
            {
                return this.dTSourceFileField;
            }
            set
            {
                this.dTSourceFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string DTStatus
        {
            get
            {
                return this.dTStatusField;
            }
            set
            {
                this.dTStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string SepName
        {
            get
            {
                return this.sepNameField;
            }
            set
            {
                this.sepNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int Scale
        {
            get
            {
                return this.scaleField;
            }
            set
            {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public double SpatialReferencingAccuracy
        {
            get
            {
                return this.spatialReferencingAccuracyField;
            }
            set
            {
                this.spatialReferencingAccuracyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface SDRAExternalInterfaceDataAccessWebServiceSoapChannel : SDRADataAccessWebService.SDRAExternalInterfaceDataAccessWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class SDRAExternalInterfaceDataAccessWebServiceSoapClient : System.ServiceModel.ClientBase<SDRADataAccessWebService.SDRAExternalInterfaceDataAccessWebServiceSoap>, SDRADataAccessWebService.SDRAExternalInterfaceDataAccessWebServiceSoap
    {
        
        public SDRAExternalInterfaceDataAccessWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.Document[]> GetDocumentsByPointAsync(SDRADataAccessWebService.Point searchPoint, int buffer, System.DateTime registrationDate, int docTypeId, int recommendedActionId)
        {
            return base.Channel.GetDocumentsByPointAsync(searchPoint, buffer, registrationDate, docTypeId, recommendedActionId);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.Document[]> GetDocumentsByLineAsync(SDRADataAccessWebService.Line searchLine, int buffer, System.DateTime registrationDate, int docTypeId, int recommendedActionId)
        {
            return base.Channel.GetDocumentsByLineAsync(searchLine, buffer, registrationDate, docTypeId, recommendedActionId);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.Document[]> GetDocumentsByPolygonAsync(SDRADataAccessWebService.Polygon searchPolygon, int buffer, System.DateTime registrationDate, int docTypeId, int recommendedActionId)
        {
            return base.Channel.GetDocumentsByPolygonAsync(searchPolygon, buffer, registrationDate, docTypeId, recommendedActionId);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.Document[]> GetDocumentsFromListAsync(int[] sdocId)
        {
            return base.Channel.GetDocumentsFromListAsync(sdocId);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.CallOutcome> GetDocumentForViewingAsync(string callerCode, int sdocId, string writeableFolderName, bool imageAsGeoTIFF)
        {
            return base.Channel.GetDocumentForViewingAsync(callerCode, sdocId, writeableFolderName, imageAsGeoTIFF);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.ProcessingStatus[]> GetDocumentRequestQueueStatusAsync(string callerCode)
        {
            return base.Channel.GetDocumentRequestQueueStatusAsync(callerCode);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.CallOutcome> ClearDocumentRequestJobFromQueueAsync(string callerCode, int sdocId, string writeableFolderName)
        {
            return base.Channel.ClearDocumentRequestJobFromQueueAsync(callerCode, sdocId, writeableFolderName);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.CallOutcome> ClearDocumentRequestQueueAsync(string callerCode)
        {
            return base.Channel.ClearDocumentRequestQueueAsync(callerCode);
        }
        
        public System.Threading.Tasks.Task<string> GetDocumentMetadataAsync(int sdocId)
        {
            return base.Channel.GetDocumentMetadataAsync(sdocId);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetDocumentRegistrationDateAsync(int sdocId)
        {
            return base.Channel.GetDocumentRegistrationDateAsync(sdocId);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.DocumentAction[]> GetDocumentAssessmentsAsync(int sdocId)
        {
            return base.Channel.GetDocumentAssessmentsAsync(sdocId);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.ArrayOfXElement> GetDocumentActionsAsync(int sdocId)
        {
            return base.Channel.GetDocumentActionsAsync(sdocId);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.Link[]> GetForwardDocumentLinksAsync(int sdocId)
        {
            return base.Channel.GetForwardDocumentLinksAsync(sdocId);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.Link[]> GetBackwardDocumentLinksAsync(int sdocId)
        {
            return base.Channel.GetBackwardDocumentLinksAsync(sdocId);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.Document[]> GetSEPDocumentLinksAsync(int sdocId)
        {
            return base.Channel.GetSEPDocumentLinksAsync(sdocId);
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.DocumentType[]> GetAllDocumentTypesAsync()
        {
            return base.Channel.GetAllDocumentTypesAsync();
        }
        
        public System.Threading.Tasks.Task<SDRADataAccessWebService.RecommendedActionType[]> GetAllRecommendedActionTypesAsync()
        {
            return base.Channel.GetAllRecommendedActionTypesAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.1")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
