//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDRAAssessmentWebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class Document : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private int DocumentTypeIdField;
        
        private string SourceNameField;
        
        private string SpatialExtentPolygonField;
        
        private int CRSIdField;
        
        private string CRSParamsField;
        
        private int DTIdField;
        
        private string DTNameField;
        
        private int DTFromDatumField;
        
        private string DTMethodField;
        
        private double DTDxField;
        
        private double DTDyField;
        
        private double DTDzField;
        
        private double DTRxField;
        
        private double DTRyField;
        
        private double DTRzField;
        
        private double DTScaleField;
        
        private double DTAccuracyField;
        
        private string DTSourceFileField;
        
        private string DTStatusField;
        
        private string SepNameField;
        
        private int ScaleField;
        
        private double SpatialReferencingAccuracyField;
        
        private int StatusField;
        
        private System.DateTime RegistrationDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DocumentTypeId
        {
            get
            {
                return this.DocumentTypeIdField;
            }
            set
            {
                this.DocumentTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SourceName
        {
            get
            {
                return this.SourceNameField;
            }
            set
            {
                this.SourceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SpatialExtentPolygon
        {
            get
            {
                return this.SpatialExtentPolygonField;
            }
            set
            {
                this.SpatialExtentPolygonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CRSId
        {
            get
            {
                return this.CRSIdField;
            }
            set
            {
                this.CRSIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CRSParams
        {
            get
            {
                return this.CRSParamsField;
            }
            set
            {
                this.CRSParamsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int DTId
        {
            get
            {
                return this.DTIdField;
            }
            set
            {
                this.DTIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DTName
        {
            get
            {
                return this.DTNameField;
            }
            set
            {
                this.DTNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int DTFromDatum
        {
            get
            {
                return this.DTFromDatumField;
            }
            set
            {
                this.DTFromDatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DTMethod
        {
            get
            {
                return this.DTMethodField;
            }
            set
            {
                this.DTMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double DTDx
        {
            get
            {
                return this.DTDxField;
            }
            set
            {
                this.DTDxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public double DTDy
        {
            get
            {
                return this.DTDyField;
            }
            set
            {
                this.DTDyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public double DTDz
        {
            get
            {
                return this.DTDzField;
            }
            set
            {
                this.DTDzField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public double DTRx
        {
            get
            {
                return this.DTRxField;
            }
            set
            {
                this.DTRxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public double DTRy
        {
            get
            {
                return this.DTRyField;
            }
            set
            {
                this.DTRyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public double DTRz
        {
            get
            {
                return this.DTRzField;
            }
            set
            {
                this.DTRzField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public double DTScale
        {
            get
            {
                return this.DTScaleField;
            }
            set
            {
                this.DTScaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public double DTAccuracy
        {
            get
            {
                return this.DTAccuracyField;
            }
            set
            {
                this.DTAccuracyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string DTSourceFile
        {
            get
            {
                return this.DTSourceFileField;
            }
            set
            {
                this.DTSourceFileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string DTStatus
        {
            get
            {
                return this.DTStatusField;
            }
            set
            {
                this.DTStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string SepName
        {
            get
            {
                return this.SepNameField;
            }
            set
            {
                this.SepNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int Scale
        {
            get
            {
                return this.ScaleField;
            }
            set
            {
                this.ScaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public double SpatialReferencingAccuracy
        {
            get
            {
                return this.SpatialReferencingAccuracyField;
            }
            set
            {
                this.SpatialReferencingAccuracyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.RegistrationDateField;
            }
            set
            {
                this.RegistrationDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallOutcome", Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class CallOutcome : object
    {
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionGroup", Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class ActionGroup : object
    {
        
        private string GroupIdField;
        
        private SDRAAssessmentWebService.ArrayOfInt ActionIDsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GroupId
        {
            get
            {
                return this.GroupIdField;
            }
            set
            {
                this.GroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SDRAAssessmentWebService.ArrayOfInt ActionIDs
        {
            get
            {
                return this.ActionIDsField;
            }
            set
            {
                this.ActionIDsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://www.baesystems.com/schemas/sdra/assessment", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Name="SDRA External Interface Assessment Web ServiceSoap", Namespace="http://www.baesystems.com/schemas/sdra/assessment", ConfigurationName="SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap")]
    public interface SDRAExternalInterfaceAssessmentWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/assessment/GetDocumentsForAssessment", ReplyAction="*")]
        System.Threading.Tasks.Task<SDRAAssessmentWebService.GetDocumentsForAssessmentResponse> GetDocumentsForAssessmentAsync(SDRAAssessmentWebService.GetDocumentsForAssessmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/assessment/GetAssessmentDueDate", ReplyAction="*")]
        System.Threading.Tasks.Task<SDRAAssessmentWebService.GetAssessmentDueDateResponse> GetAssessmentDueDateAsync(SDRAAssessmentWebService.GetAssessmentDueDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/assessment/NotifyDocumentAssessed", ReplyAction="*")]
        System.Threading.Tasks.Task<SDRAAssessmentWebService.NotifyDocumentAssessedResponse> NotifyDocumentAssessedAsync(SDRAAssessmentWebService.NotifyDocumentAssessedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/assessment/NotifyAssessmentCompleted", ReplyAction="*")]
        System.Threading.Tasks.Task<SDRAAssessmentWebService.NotifyAssessmentCompletedResponse> NotifyAssessmentCompletedAsync(SDRAAssessmentWebService.NotifyAssessmentCompletedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baesystems.com/schemas/sdra/assessment/SetActionGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<SDRAAssessmentWebService.SetActionGroupsResponse> SetActionGroupsAsync(SDRAAssessmentWebService.SetActionGroupsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentsForAssessmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentsForAssessment", Namespace="http://www.baesystems.com/schemas/sdra/assessment", Order=0)]
        public SDRAAssessmentWebService.GetDocumentsForAssessmentRequestBody Body;
        
        public GetDocumentsForAssessmentRequest()
        {
        }
        
        public GetDocumentsForAssessmentRequest(SDRAAssessmentWebService.GetDocumentsForAssessmentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class GetDocumentsForAssessmentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string callerCode;
        
        public GetDocumentsForAssessmentRequestBody()
        {
        }
        
        public GetDocumentsForAssessmentRequestBody(string callerCode)
        {
            this.callerCode = callerCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentsForAssessmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentsForAssessmentResponse", Namespace="http://www.baesystems.com/schemas/sdra/assessment", Order=0)]
        public SDRAAssessmentWebService.GetDocumentsForAssessmentResponseBody Body;
        
        public GetDocumentsForAssessmentResponse()
        {
        }
        
        public GetDocumentsForAssessmentResponse(SDRAAssessmentWebService.GetDocumentsForAssessmentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class GetDocumentsForAssessmentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SDRAAssessmentWebService.Document[] GetDocumentsForAssessmentResult;
        
        public GetDocumentsForAssessmentResponseBody()
        {
        }
        
        public GetDocumentsForAssessmentResponseBody(SDRAAssessmentWebService.Document[] GetDocumentsForAssessmentResult)
        {
            this.GetDocumentsForAssessmentResult = GetDocumentsForAssessmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAssessmentDueDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAssessmentDueDate", Namespace="http://www.baesystems.com/schemas/sdra/assessment", Order=0)]
        public SDRAAssessmentWebService.GetAssessmentDueDateRequestBody Body;
        
        public GetAssessmentDueDateRequest()
        {
        }
        
        public GetAssessmentDueDateRequest(SDRAAssessmentWebService.GetAssessmentDueDateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class GetAssessmentDueDateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string callerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sdocId;
        
        public GetAssessmentDueDateRequestBody()
        {
        }
        
        public GetAssessmentDueDateRequestBody(string callerCode, int sdocId)
        {
            this.callerCode = callerCode;
            this.sdocId = sdocId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAssessmentDueDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAssessmentDueDateResponse", Namespace="http://www.baesystems.com/schemas/sdra/assessment", Order=0)]
        public SDRAAssessmentWebService.GetAssessmentDueDateResponseBody Body;
        
        public GetAssessmentDueDateResponse()
        {
        }
        
        public GetAssessmentDueDateResponse(SDRAAssessmentWebService.GetAssessmentDueDateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class GetAssessmentDueDateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime GetAssessmentDueDateResult;
        
        public GetAssessmentDueDateResponseBody()
        {
        }
        
        public GetAssessmentDueDateResponseBody(System.DateTime GetAssessmentDueDateResult)
        {
            this.GetAssessmentDueDateResult = GetAssessmentDueDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyDocumentAssessedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyDocumentAssessed", Namespace="http://www.baesystems.com/schemas/sdra/assessment", Order=0)]
        public SDRAAssessmentWebService.NotifyDocumentAssessedRequestBody Body;
        
        public NotifyDocumentAssessedRequest()
        {
        }
        
        public NotifyDocumentAssessedRequest(SDRAAssessmentWebService.NotifyDocumentAssessedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class NotifyDocumentAssessedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string callerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string transactionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int sdocId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int prodId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] snapshot;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string action;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string change;
        
        public NotifyDocumentAssessedRequestBody()
        {
        }
        
        public NotifyDocumentAssessedRequestBody(string callerCode, string transactionId, int sdocId, int prodId, byte[] snapshot, string action, string change)
        {
            this.callerCode = callerCode;
            this.transactionId = transactionId;
            this.sdocId = sdocId;
            this.prodId = prodId;
            this.snapshot = snapshot;
            this.action = action;
            this.change = change;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyDocumentAssessedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyDocumentAssessedResponse", Namespace="http://www.baesystems.com/schemas/sdra/assessment", Order=0)]
        public SDRAAssessmentWebService.NotifyDocumentAssessedResponseBody Body;
        
        public NotifyDocumentAssessedResponse()
        {
        }
        
        public NotifyDocumentAssessedResponse(SDRAAssessmentWebService.NotifyDocumentAssessedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class NotifyDocumentAssessedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SDRAAssessmentWebService.CallOutcome NotifyDocumentAssessedResult;
        
        public NotifyDocumentAssessedResponseBody()
        {
        }
        
        public NotifyDocumentAssessedResponseBody(SDRAAssessmentWebService.CallOutcome NotifyDocumentAssessedResult)
        {
            this.NotifyDocumentAssessedResult = NotifyDocumentAssessedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyAssessmentCompletedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyAssessmentCompleted", Namespace="http://www.baesystems.com/schemas/sdra/assessment", Order=0)]
        public SDRAAssessmentWebService.NotifyAssessmentCompletedRequestBody Body;
        
        public NotifyAssessmentCompletedRequest()
        {
        }
        
        public NotifyAssessmentCompletedRequest(SDRAAssessmentWebService.NotifyAssessmentCompletedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class NotifyAssessmentCompletedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string callerCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sdocId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string comment;
        
        public NotifyAssessmentCompletedRequestBody()
        {
        }
        
        public NotifyAssessmentCompletedRequestBody(string callerCode, int sdocId, string comment)
        {
            this.callerCode = callerCode;
            this.sdocId = sdocId;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyAssessmentCompletedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyAssessmentCompletedResponse", Namespace="http://www.baesystems.com/schemas/sdra/assessment", Order=0)]
        public SDRAAssessmentWebService.NotifyAssessmentCompletedResponseBody Body;
        
        public NotifyAssessmentCompletedResponse()
        {
        }
        
        public NotifyAssessmentCompletedResponse(SDRAAssessmentWebService.NotifyAssessmentCompletedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class NotifyAssessmentCompletedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SDRAAssessmentWebService.CallOutcome NotifyAssessmentCompletedResult;
        
        public NotifyAssessmentCompletedResponseBody()
        {
        }
        
        public NotifyAssessmentCompletedResponseBody(SDRAAssessmentWebService.CallOutcome NotifyAssessmentCompletedResult)
        {
            this.NotifyAssessmentCompletedResult = NotifyAssessmentCompletedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetActionGroupsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetActionGroups", Namespace="http://www.baesystems.com/schemas/sdra/assessment", Order=0)]
        public SDRAAssessmentWebService.SetActionGroupsRequestBody Body;
        
        public SetActionGroupsRequest()
        {
        }
        
        public SetActionGroupsRequest(SDRAAssessmentWebService.SetActionGroupsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class SetActionGroupsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sdocId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SDRAAssessmentWebService.ActionGroup[] groups;
        
        public SetActionGroupsRequestBody()
        {
        }
        
        public SetActionGroupsRequestBody(int sdocId, SDRAAssessmentWebService.ActionGroup[] groups)
        {
            this.sdocId = sdocId;
            this.groups = groups;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetActionGroupsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetActionGroupsResponse", Namespace="http://www.baesystems.com/schemas/sdra/assessment", Order=0)]
        public SDRAAssessmentWebService.SetActionGroupsResponseBody Body;
        
        public SetActionGroupsResponse()
        {
        }
        
        public SetActionGroupsResponse(SDRAAssessmentWebService.SetActionGroupsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baesystems.com/schemas/sdra/assessment")]
    public partial class SetActionGroupsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SDRAAssessmentWebService.CallOutcome SetActionGroupsResult;
        
        public SetActionGroupsResponseBody()
        {
        }
        
        public SetActionGroupsResponseBody(SDRAAssessmentWebService.CallOutcome SetActionGroupsResult)
        {
            this.SetActionGroupsResult = SetActionGroupsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface SDRAExternalInterfaceAssessmentWebServiceSoapChannel : SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class SDRAExternalInterfaceAssessmentWebServiceSoapClient : System.ServiceModel.ClientBase<SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap>, SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap
    {
        
        public SDRAExternalInterfaceAssessmentWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDRAAssessmentWebService.GetDocumentsForAssessmentResponse> SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap.GetDocumentsForAssessmentAsync(SDRAAssessmentWebService.GetDocumentsForAssessmentRequest request)
        {
            return base.Channel.GetDocumentsForAssessmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDRAAssessmentWebService.GetDocumentsForAssessmentResponse> GetDocumentsForAssessmentAsync(string callerCode)
        {
            SDRAAssessmentWebService.GetDocumentsForAssessmentRequest inValue = new SDRAAssessmentWebService.GetDocumentsForAssessmentRequest();
            inValue.Body = new SDRAAssessmentWebService.GetDocumentsForAssessmentRequestBody();
            inValue.Body.callerCode = callerCode;
            return ((SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap)(this)).GetDocumentsForAssessmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDRAAssessmentWebService.GetAssessmentDueDateResponse> SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap.GetAssessmentDueDateAsync(SDRAAssessmentWebService.GetAssessmentDueDateRequest request)
        {
            return base.Channel.GetAssessmentDueDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDRAAssessmentWebService.GetAssessmentDueDateResponse> GetAssessmentDueDateAsync(string callerCode, int sdocId)
        {
            SDRAAssessmentWebService.GetAssessmentDueDateRequest inValue = new SDRAAssessmentWebService.GetAssessmentDueDateRequest();
            inValue.Body = new SDRAAssessmentWebService.GetAssessmentDueDateRequestBody();
            inValue.Body.callerCode = callerCode;
            inValue.Body.sdocId = sdocId;
            return ((SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap)(this)).GetAssessmentDueDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDRAAssessmentWebService.NotifyDocumentAssessedResponse> SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap.NotifyDocumentAssessedAsync(SDRAAssessmentWebService.NotifyDocumentAssessedRequest request)
        {
            return base.Channel.NotifyDocumentAssessedAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDRAAssessmentWebService.NotifyDocumentAssessedResponse> NotifyDocumentAssessedAsync(string callerCode, string transactionId, int sdocId, int prodId, byte[] snapshot, string action, string change)
        {
            SDRAAssessmentWebService.NotifyDocumentAssessedRequest inValue = new SDRAAssessmentWebService.NotifyDocumentAssessedRequest();
            inValue.Body = new SDRAAssessmentWebService.NotifyDocumentAssessedRequestBody();
            inValue.Body.callerCode = callerCode;
            inValue.Body.transactionId = transactionId;
            inValue.Body.sdocId = sdocId;
            inValue.Body.prodId = prodId;
            inValue.Body.snapshot = snapshot;
            inValue.Body.action = action;
            inValue.Body.change = change;
            return ((SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap)(this)).NotifyDocumentAssessedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDRAAssessmentWebService.NotifyAssessmentCompletedResponse> SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap.NotifyAssessmentCompletedAsync(SDRAAssessmentWebService.NotifyAssessmentCompletedRequest request)
        {
            return base.Channel.NotifyAssessmentCompletedAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDRAAssessmentWebService.NotifyAssessmentCompletedResponse> NotifyAssessmentCompletedAsync(string callerCode, int sdocId, string comment)
        {
            SDRAAssessmentWebService.NotifyAssessmentCompletedRequest inValue = new SDRAAssessmentWebService.NotifyAssessmentCompletedRequest();
            inValue.Body = new SDRAAssessmentWebService.NotifyAssessmentCompletedRequestBody();
            inValue.Body.callerCode = callerCode;
            inValue.Body.sdocId = sdocId;
            inValue.Body.comment = comment;
            return ((SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap)(this)).NotifyAssessmentCompletedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SDRAAssessmentWebService.SetActionGroupsResponse> SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap.SetActionGroupsAsync(SDRAAssessmentWebService.SetActionGroupsRequest request)
        {
            return base.Channel.SetActionGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SDRAAssessmentWebService.SetActionGroupsResponse> SetActionGroupsAsync(int sdocId, SDRAAssessmentWebService.ActionGroup[] groups)
        {
            SDRAAssessmentWebService.SetActionGroupsRequest inValue = new SDRAAssessmentWebService.SetActionGroupsRequest();
            inValue.Body = new SDRAAssessmentWebService.SetActionGroupsRequestBody();
            inValue.Body.sdocId = sdocId;
            inValue.Body.groups = groups;
            return ((SDRAAssessmentWebService.SDRAExternalInterfaceAssessmentWebServiceSoap)(this)).SetActionGroupsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
