trigger:
- master

variables:
- group: msbuildexe

pool: NautilusBuild

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.x'
    checkLatest: true
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'    
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity.mgmt.local'
    projectName: 'TaskManager'
    streamName: 'TaskManager-master'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    buildCommand: '$(msbuild) src\TaskManager.sln'
    customCommandArgs: true
    covAnalyzeArgs: '--webapp-security'
