trigger:
- master

variables:
- group: msbuildexe

pool: NautilusBuild

steps:
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity.mgmt.local'
    projectName: 'TaskManager'
    streamName: 'TaskManager-master'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    buildCommand: '$(msbuild) "$(Build.Repository.LocalPath)\src\TaskManager.sln" /build'
    customCommandArgs: true
    covAnalyzeArgs: '--webapp-security'
