trigger:
- master

variables:
- group: msbuildexe

pool: NautilusBuild

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity.mgmt.local'
    projectName: 'TaskManager'
    streamName: 'TaskManager-master'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    buildCommand: 'dotnetcore build src\TaskManager.sln'
    customCommandArgs: true
    covAnalyzeArgs: '--webapp-security'
