trigger:
  branches:
    include:
    - master
    - features/*
  paths:
    include:
    - src/SourceDocumentCoordinator/*
    - src/Databases/WorkflowDatabase.EF/*
    - src/Common*

stages:
- stage: Build
  jobs:
    - job: RestoreBuildAndDeploy
      pool: "UKHO Windows 2019"

      workspace:
          clean: all

      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core 3.1.x SDK'
        inputs:
          packageType: sdk
          version: 3.1.x
          installationPath: $(Agent.ToolsDirectory)\\dotnet

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '$(Build.SourcesDirectory)\\src\\sourcedocumentcoordinator\\sourcedocumentcoordinator\\sourcedocumentcoordinator.csproj'
          feedsToUse: 'select'
        displayName: 'dotnet restore sourcedocumentcoordinator'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '$(Build.SourcesDirectory)\\src\\sourcedocumentcoordinator\\sourcedocumentcoordinator\\sourcedocumentcoordinator.csproj'
        displayName: 'dotnet build sourcedocumentcoordinator'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '$(Build.SourcesDirectory)\\src\\sourcedocumentcoordinator\\sourcedocumentcoordinator.unittests\\sourcedocumentcoordinator.unittests.csproj'
          feedsToUse: 'select'
        displayName: 'dotnet restore sourcedocumentcoordinatortests'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '$(Build.SourcesDirectory)\\src\\sourcedocumentcoordinator\\sourcedocumentcoordinator.unittests\\sourcedocumentcoordinator.unittests.csproj'
        displayName: 'dotnet build sourcedocumentcoordinatortests'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '$(Build.SourcesDirectory)\\src\\sourcedocumentcoordinator\\sourcedocumentcoordinator.unittests\\sourcedocumentcoordinator.unittests.csproj'
          arguments: -c $(BuildConfiguration) --collect:"XPlat Code Coverage" -s $(Build.SourcesDirectory)\\src\\sourcedocumentcoordinator\\sourcedocumentcoordinator.unittests\\CodeCoverage.runsettings
        displayName: 'dotnet test sourcedocumentcoordinatortests'

      - task: DotNetCoreCLI@2
        inputs:
          command: custom
          custom: tool
          arguments: install --tool-path . dotnet-reportgenerator-globaltool
        displayName: Install ReportGenerator tool

      - script: reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"
        displayName: Create reports
        
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(Build.SourcesDirectory)\coverlet\reports\Cobertura.xml

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '$(Build.SourcesDirectory)\\src\\sourcedocumentcoordinator\\sourcedocumentcoordinator\\sourcedocumentcoordinator.csproj'
          zipAfterPublish: false
          arguments: '--output $(Build.ArtifactStagingDirectory)\\WebJob\\App_Data\\jobs\\continuous'
        displayName: 'Publish Solution'

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: '"dotnet sourcedocumentcoordinator.dll" | Out-File run.cmd -Encoding ASCII; $LASTEXITCODE'
          workingDirectory: '$(Build.ArtifactStagingDirectory)\\WebJob\\App_Data\\jobs\\continuous\\sourcedocumentcoordinator'
        displayName: 'Generate run.cmd'

      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'License.xml'
        name: 'nsblicense'
        displayName: 'Download NSB License from Secure Files'

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'copy-item $(nsblicense.secureFilePath) .\\'
          workingDirectory: '$(Build.ArtifactStagingDirectory)\\WebJob\\App_Data\\jobs\\continuous\\sourcedocumentcoordinator'
        displayName: 'Copy NSB License'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'sourcedocumentcoordinator'
          publishLocation: 'Container'
        displayName: 'Publish sourcedocumentcoordinator Artifact'

- stage: DeployDev
  jobs:
    - deployment: DeploySourceDocumentCoordinator
      displayName: Deploy Web App
      pool: "UKHO Windows 2019"
      environment: 'TaskmanagerDev'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureRmWebAppDeployment@4
                displayName: 'Azure App Service Deploy'
                inputs:
                  azureSubscription: 'TaskmanagerDev'
                  WebAppName: 'taskmanager-dev-nsb-sdoccoordinator'
                  packageForLinux: '$(Pipeline.Workspace)/sourcedocumentcoordinator/WebJob'

- stage: DeployUAT
  jobs:
    - deployment: DeploySourceDocumentCoordinator
      displayName: Deploy Web App
      pool: "UKHO Windows 2019"
      environment: 'TaskmanagerUAT'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureRmWebAppDeployment@4
                displayName: 'Azure App Service Deploy'
                inputs:
                  azureSubscription: 'TaskmanagerUAT-SC'
                  WebAppName: 'taskmanager-uat-nsb-sdoccoordinator'
                  packageForLinux: '$(Pipeline.Workspace)/sourcedocumentcoordinator/WebJob'

- stage: DeployPre
  jobs:
    - deployment: DeploySourceDocumentCoordinator
      displayName: Deploy Web App
      pool: "UKHO Windows 2019"
      environment: 'TaskmanagerPre'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureRmWebAppDeployment@4
                displayName: 'Azure App Service Deploy'
                inputs:
                  azureSubscription: 'TaskmanagerPre-SC'
                  WebAppName: 'taskmanager-pre-nsb-sdoccoordinator'
                  packageForLinux: '$(Pipeline.Workspace)/sourcedocumentcoordinator/WebJob'
