trigger:
- master

pool:
  name: 'UKHO Windows 2019'

steps:

- powershell: dotnet restore $(Build.SourcesDirectory)\taskmanager\workflowcoordinator\workflowcoordinator.csproj
  displayName: Restore Workflow Coordinator packages

- powershell: dotnet restore $(Build.SourcesDirectory)\taskmanager\workflowcoordinatortests\workflowcoordinatortests.csproj
  displayName: Restore Workflow Coordinator test packages

- powershell: dotnet build $(Build.SourcesDirectory)\taskmanager\workflowcoordinator\workflowcoordinator.csproj --no-restore
  displayName: Build Workflow Coordinator

- powershell: dotnet build $(Build.SourcesDirectory)\taskmanager\workflowcoordinatortests\workflowcoordinatortests.csproj --no-restore
  displayName: Build Workflow Coordinator Tests

- powershell: dotnet test $(Build.SourcesDirectory)\taskmanager\workflowcoordinatortests\workflowcoordinatortests.csproj --no-build --logger:trx -r $(Agent.BuildDirectory)/TestResults 
  displayName: Test Workflow Coordinator

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: '$(Agent.BuildDirectory)/TestResults/*.trx'
    failTaskOnFailedTests: true
    mergeTestResults: true

- powershell: dotnet publish $(Build.SourcesDirectory)\taskmanager\workflowcoordinator\workflowcoordinator.csproj --no-build --output $(Build.ArtifactStagingDirectory)\workflowCoordinator
  displayName: Publish Workflow Coordinator

- powershell: '"dotnet workflowcoordinator.dll" | Out-File run.cmd -Encoding ASCII; $LASTEXITCODE'
  workingDirectory: $(Build.ArtifactStagingDirectory)\workflowCoordinator\'  
  displayName: Generate run.cmd

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'workflowcoordinator'
#     publishLocation: 'Container'
#   displayName: 'Publish workflowcoordinator Artifact'

