variables:
  workflowCoordinator: $(Build.SourcesDirectory)\taskmanager\workflowcoordinator\workflowcoordinator.csproj
  workflowCoordinatorTests: $(Build.SourcesDirectory)\taskmanager\workflowcoordinatortests\workflowcoordinatortests.csproj
  taskmanagerDir: $(Build.SourcesDirectory)\TaskManager
  taskmanagerSln: $(taskmanagerDir)\TaskManager.sln
  configuration: Release

trigger:
- master

pool:
  name: 'UKHO Windows 2019'

steps:

- powershell: |
    dotnet sln remove (dir **/*.csproj)
    dotnet sln add $(workflowCoordinator) $(workflowCoordinatorTests)
  workingDirectory: $(taskmanagerDir)
  displayName: Remove all .csprojs and add relevent projects
  
- powershell: dotnet restore $(taskmanagerSln)
  displayName: Restore packages

- powershell: dotnet build $(taskmanagerSln) --no-restore -c $(configuration)
  displayName: Build Workflow Coordinator Tests

- powershell: dotnet test $(taskmanagerSln) --no-build -c $(configuration) --logger:trx -r $(Agent.BuildDirectory)/TestResults 
  displayName: Test Workflow Coordinator

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: '$(Agent.BuildDirectory)/TestResults/*.trx'
    failTaskOnFailedTests: true
    mergeTestResults: true

- powershell: dotnet publish $(workflowCoordinator) --no-build --output $(Build.ArtifactStagingDirectory)\workflowCoordinator
  displayName: Publish Workflow Coordinator

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'License.xml'
  name: 'nsblicense'
  displayName: 'Download NSB License from Secure Files'

- powershell: copy-item $(nsblicense.secureFilePath) .\
  workingDirectory: $(Build.ArtifactStagingDirectory)\workflowCoordinator 
  displayName: Copy NSB License into the artifact 

- powershell: '"dotnet workflowcoordinator.dll" | Out-File run.cmd -Encoding ASCII; $LASTEXITCODE'
  workingDirectory: $(Build.ArtifactStagingDirectory)\workflowCoordinator  
  displayName: Generate run.cmd and add to the artifact

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: workflowcoordinator
  displayName: Publish workflowcoordinator Artifact

